Repository credebl/platform, pull requests merged in 2023-11, with the labels that each got.

#238 Security vulnerability fixes
  apps/api-gateway/src/main.ts
  package-lock.json
  package.json
Labels: security issue

#242 Sort organizations in descending order based on their name
  apps/organization/repositories/organization.repository.ts
Labels: enhancement

#255 Disallowed dummy email domains
  apps/user/src/user.service.ts
  libs/common/src/common.constant.ts
  libs/common/src/response-messages/index.ts
Labels: enhancement

#259 security-fix:Configured helmet for X-Xss-Protection
  apps/api-gateway/src/main.ts
Labels: security issue

#249 Fix:Added SQL Injection Mitigation Techniques
  apps/user/src/user.service.ts
  package-lock.json
  package.json
Labels: security issue

#260 fix:modified dtos class validators messages
  apps/api-gateway/src/user/dto/add-user.dto.ts
Labels: bug

#268 feat: Share user certificate
  apps/api-gateway/src/issuance/dtos/issuance.dto.ts
  apps/api-gateway/src/organization/organization.controller.ts
  apps/api-gateway/src/organization/organization.service.ts
  apps/api-gateway/src/user/dto/share-certificate.dto.ts
  apps/api-gateway/src/user/user.controller.ts
  apps/api-gateway/src/user/user.module.ts
  apps/api-gateway/src/user/user.service.ts
  apps/user/interfaces/user.interface.ts
  apps/user/repositories/user.repository.ts
  apps/user/src/fido/fido.module.ts
  apps/user/src/user.controller.ts
  apps/user/src/user.module.ts
  apps/user/src/user.service.ts
  apps/user/templates/arbiter-template.ts
  apps/user/templates/participant-template.ts
  apps/user/templates/winner-template.ts
  apps/user/templates/world-record-template.ts
  libs/aws/src/aws.service.ts
  libs/common/src/response-messages/index.ts
  libs/enum/src/enum.ts
  libs/image-service/src/image-service.service.ts
  libs/prisma-service/prisma/migrations/20231109044921_user_credentials/migration.sql
  libs/prisma-service/prisma/migrations/20231120132943_credential_id_unique/migration.sql
  libs/prisma-service/prisma/schema.prisma
  package.json
  pnpm-lock.yaml
Labels: enhancement

#271 refactor: added puppeteer configuration
  apps/user/src/user.service.ts
Labels: enhancement

#277 refactor: Resolved puppeteer library issues
  Dockerfiles/Dockerfile.user
  apps/api-gateway/src/organization/organization.controller.ts
  apps/api-gateway/src/organization/organization.service.ts
  apps/user/src/user.service.ts
  apps/user/templates/winner-template.ts
  package.json
  pnpm-lock.yaml
Labels: enhancement

#286 refactor: developed new certificate html templates
  apps/api-gateway/src/user/user.controller.ts
  apps/user/src/user.service.ts
  apps/user/templates/arbiter-template.ts
  apps/user/templates/participant-template.ts
  apps/user/templates/winner-template.ts
  apps/user/templates/world-record-template.ts
  libs/aws/src/aws.service.ts
  libs/common/src/interfaces/response.interface.ts
  libs/enum/src/enum.ts
Labels: enhancement

#284 refact:added function for validating emails from uploaded file in bulk issuance API
  apps/issuance/src/issuance.service.ts
Labels: enhancement

#290 Error message emitted during the bulk issuance process failed through sockets
  apps/api-gateway/src/authz/socket.gateway.ts
  apps/issuance/src/issuance.service.ts
Labels: enhancement

#292 refactor: Resolved puppeteer library issue
  apps/user/src/user.service.ts
  apps/user/templates/arbiter-template.ts
  apps/user/templates/participant-template.ts
  apps/user/templates/winner-template.ts
  apps/user/templates/world-record-template.ts
  libs/aws/src/aws.service.ts
Labels: enhancement

#295 Accept credential through deep linking
  apps/issuance/src/issuance.service.ts
  apps/issuance/templates/out-of-band-issuance.template.ts
Labels: enhancement

#296 refactor: user certificate templates
  apps/user/templates/arbiter-template.ts
  apps/user/templates/participant-template.ts
  apps/user/templates/winner-template.ts
  apps/user/templates/world-record-template.ts
Labels: enhancement

#298 refact:changed email template and added social media logo
  apps/issuance/templates/out-of-band-issuance.template.ts
Labels: enhancement
