Repository credebl/platform, pull requests merged in 2024-10, with the labels that each got.

#1025 chore: change google chrome to chromium executables
  apps/user/src/user.service.ts
Labels: enhancement

#1026 fix: increase size for org name and org description
  apps/api-gateway/src/organization/dtos/create-organization-dto.ts
  apps/api-gateway/src/organization/dtos/update-organization-dto.ts
Labels: enhancement

#1024 fix: add agent-env and attach agent-env to container when starting locally
  agent.env
  apps/agent-provisioning/AFJ/scripts/start_agent.sh
Labels: bug

#1040 fix: add agent-env and attach agent-env to container when starting locally
  agent.env
  apps/agent-provisioning/AFJ/scripts/start_agent.sh
Labels: bug

#1042 hotfix:schema creation issue for polygon mainnet
  libs/common/src/common.constant.ts
  libs/common/src/common.utils.ts
  libs/prisma-service/prisma/data/credebl-master-table.json
Labels: bug, enhancement

#1043 fix: auto start platform services with docker-compose
  .env.demo
  agent.env
  apps/agent-provisioning/AFJ/scripts/docker_start_agent.sh
  apps/agent-provisioning/AFJ/scripts/start_agent.sh
  docker-compose.yml
Labels: bug, enhancement

#1048 Create OSSF scorecard.yml
  .github/workflows/scorecard.yml
Labels: enhancement

#1049 chore: update license
  LICENSE
Labels: enhancement

#1050 chore: transition from Blockster Labs to Ayanworks
  LICENSE
  README.md
Labels: documentation
