Repository credebl/platform, pull requests merged in 2025-04, with the labels that each got.

#1164 refactor: remove image-service from libs
  apps/api-gateway/src/issuance/issuance.module.ts
  apps/api-gateway/src/organization/organization.controller.ts
  apps/api-gateway/src/organization/organization.module.ts
  apps/api-gateway/src/organization/organization.service.ts
  apps/api-gateway/src/utilities/utilities.module.ts
  apps/api-gateway/src/verification/verification.controller.ts
  apps/api-gateway/src/verification/verification.module.ts
  libs/image-service/src/image-service.module.ts
  libs/image-service/src/image-service.service.spec.ts
  libs/image-service/src/image-service.service.ts
  libs/image-service/src/index.ts
  libs/image-service/tsconfig.lib.json
  nest-cli.json
  package.json
  tsconfig.json
Labels: enhancement

#1155 fix: local setup issues
  .env.demo
  apps/agent-provisioning/AFJ/scripts/start_agent.sh
Labels: bug

#1170 docs: fix readme typo
  README.md
Labels: documentation

#1198 chore: update .env.demo file
  .env.demo
Labels: documentation

#1205 Update .env.demo
  .env.demo
Labels: bug
